import fs from "node:fs/promises";
import path from "node:path";
import { prisma } from "./prisma";

type CursorSkill = {
  name: string;
  years: number | null;
  source: string;
};

type CursorCommit = {
  shortHash: string;
  message: string;
  tags: unknown;
  repository: { name: string };
};

type CursorDecision = {
  title: string;
  description: string;
};

function stringArray(value: unknown) {
  return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : [];
}

export async function buildCursorContext() {
  const profile = await prisma.userProfile.findFirst();
  const rawSkills = await prisma.skill.findMany({ orderBy: [{ years: "desc" }, { name: "asc" }] });
  const rawRecentCommits = await prisma.commit.findMany({
    include: { repository: true },
    orderBy: { committedAt: "desc" },
    take: 12,
  });
  const rawDecisions = await prisma.decision.findMany({ orderBy: { createdAt: "desc" }, take: 10 });

  const skills = rawSkills as CursorSkill[];
  const recentCommits = rawRecentCommits as CursorCommit[];
  const decisions = rawDecisions as CursorDecision[];

  return `# Cursor Project Memory

Generated by DevMind. Treat this as grounded context, not as a replacement for inspecting code.

## Developer
- Name: ${profile?.name ?? "João Magalhães"}
- Role: ${profile?.role ?? "Software Engineer"}
- Portfolio: ${profile?.portfolio ?? "https://magalhaescode.netlify.app/"}
- LinkedIn: ${profile?.linkedin ?? "https://www.linkedin.com/in/joaomagalhaes2001"}

## Working style
- Be direct, practical, and concise.
- Prefer incremental changes over rewrites.
- Do not overengineer.
- Inspect existing architecture before proposing major changes.
- Do not invent skills, business rules, or project decisions.

## Confirmed / evidenced skills
${skills.map((skill: CursorSkill) => `- ${skill.name}${skill.years ? `: ${skill.years} years` : ""} (${skill.source})`).join("\n")}

## Recent commits
${recentCommits.map((commit: CursorCommit) => `- ${commit.repository.name} ${commit.shortHash}: ${commit.message} [${stringArray(commit.tags).join(", ")}]`).join("\n") || "- No commits captured yet."}

## Recent decisions
${decisions.map((decision: CursorDecision) => `- ${decision.title}: ${decision.description}`).join("\n") || "- No decisions recorded yet."}
`;
}

export async function writeCursorContext(repoPath: string) {
  const content = await buildCursorContext();
  const cursorDir = path.join(repoPath, ".cursor", "rules");
  await fs.mkdir(cursorDir, { recursive: true });
  const target = path.join(cursorDir, "devmind-memory.mdc");
  await fs.writeFile(target, content, "utf8");
  await fs.writeFile(path.join(repoPath, "AI_CONTEXT.md"), content, "utf8");
  return target;
}
