import fs from "node:fs/promises";
import path from "node:path";
import { prisma } from "./prisma";

export async function buildCursorContext() {
  const profile = await prisma.userProfile.findFirst();
  const skills = await prisma.skill.findMany({ orderBy: [{ years: "desc" }, { name: "asc" }] });
  const recentCommits = await prisma.commit.findMany({
    include: { repository: true },
    orderBy: { committedAt: "desc" },
    take: 12,
  });
  const decisions = await prisma.decision.findMany({ orderBy: { createdAt: "desc" }, take: 10 });

  return `# Cursor Project Memory

Generated by DevMind. Treat this as grounded context, not as a replacement for inspecting code.

## Developer
- Name: ${profile?.name ?? "João Magalhães"}
- Role: ${profile?.role ?? "Software Engineer"}
- Portfolio: ${profile?.portfolio ?? "https://magalhaescode.netlify.app/"}
- LinkedIn: ${profile?.linkedin ?? "https://www.linkedin.com/in/joaomagalhaes2001"}

## Working style
- Be direct, practical, and concise.
- Prefer incremental changes over rewrites.
- Do not overengineer.
- Inspect existing architecture before proposing major changes.
- Do not invent skills, business rules, or project decisions.

## Confirmed / evidenced skills
${skills.map((s) => `- ${s.name}${s.years ? `: ${s.years} years` : ""} (${s.source})`).join("\n")}

## Recent commits
${recentCommits.map((c) => `- ${c.repository.name} ${c.shortHash}: ${c.message} [${(c.tags as string[]).join(", ")}]`).join("\n") || "- No commits captured yet."}

## Recent decisions
${decisions.map((d) => `- ${d.title}: ${d.description}`).join("\n") || "- No decisions recorded yet."}
`;
}

export async function writeCursorContext(repoPath: string) {
  const content = await buildCursorContext();
  const cursorDir = path.join(repoPath, ".cursor", "rules");
  await fs.mkdir(cursorDir, { recursive: true });
  const target = path.join(cursorDir, "devmind-memory.mdc");
  await fs.writeFile(target, content, "utf8");
  await fs.writeFile(path.join(repoPath, "AI_CONTEXT.md"), content, "utf8");
  return target;
}
