import fs from "node:fs/promises";
import path from "node:path";
import { prisma } from "../src/lib/prisma";
import { writeCursorContext } from "../src/lib/cursor-context";

function slugify(input: string) {
  return input.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

async function exists(file: string) {
  try { await fs.access(file); return true; } catch { return false; }
}

async function main() {
  const rawName = process.argv[2];
  if (!rawName) {
    console.error("Usage: npm run project:new -- \"Project Name\" [stack,csv]");
    process.exit(1);
  }

  const stack = (process.argv[3] ?? "").split(",").map((s) => s.trim()).filter(Boolean);
  const slug = slugify(rawName);
  const projectPath = path.resolve("apps", slug);

  await fs.mkdir(path.join(projectPath, ".cursor", "rules"), { recursive: true });
  await fs.mkdir(path.join(projectPath, "src"), { recursive: true });

  const files: Record<string, string> = {
    "README.md": `# ${rawName}\n\nProject workspace generated by DevMind.\n\n## Stack\n\n${stack.length ? stack.map((s) => `- ${s}`).join("\n") : "- TBD"}\n`,
    "PROJECT.md": `# ${rawName} — Project Context\n\n## Goal\n\nTBD.\n\n## Constraints\n\n- Keep work inside this repository unless João says otherwise.\n- Do not add secrets to git.\n- Prefer practical, incremental implementation.\n\n## Decisions\n\n- Created as part of the single-repo multi-project workspace.\n`,
    "TODO.md": `# TODO\n\n- [ ] Define MVP scope\n- [ ] Choose final stack\n- [ ] Implement first vertical slice\n`,
    ".gitkeep": "",
  };

  for (const [relative, content] of Object.entries(files)) {
    const target = path.join(projectPath, relative);
    if (!(await exists(target))) await fs.writeFile(target, content, "utf8");
  }

  await prisma.repository.upsert({
    where: { path: projectPath },
    update: { name: rawName, stack },
    create: { name: rawName, path: projectPath, stack },
  });

  await writeCursorContext(projectPath).catch(() => null);

  console.log(JSON.stringify({ ok: true, name: rawName, slug, path: projectPath }, null, 2));
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
}).finally(() => prisma.$disconnect());
